//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CokluAdisyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        public int HesapID { get; set; }
        public int Siparis_ID { get; set; }
        public int OdemeTuru { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<double> Tutar { get; set; }
    
        public virtual Siparis Siparis { get; set; }
    }
}
