//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CokluAdisyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int UrunID { get; set; }
        public int UrunGrup_ID { get; set; }
        public int Kafe_ID { get; set; }
        public string UrunAdi { get; set; }
        public float UrunFiyati { get; set; }
    
        public virtual Kafeler Kafeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
        public virtual UrunGruplari UrunGruplari { get; set; }
    }
}
